handy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include("home.urls")),
    path('admin/', admin.site.urls),
    path('workers/', include("workers.urls")),
    path('occupations/', include("occupations.urls")),
    path('user/', include("user.urls")),
    path('contract/', include("contract.urls")),
    path('jobs/', include("jobs.urls")),
    path('notifications/', include("notifications.urls")),
    path('messages/', include("message.urls")),
    path('settings/', include("settings.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomePageView

app_name = "home"
urlpatterns = [
	path("",HomePageView.as_view(),name="index")
]

message/urls.py
from django.urls import path, include
from .views import *

app_name = "message"
urlpatterns = [
	path("",MessageInboxView.as_view(),name="list"),
	path("<person>/",MessageView,name="message"),
	path("<recepient>/send/",MessageSendView.as_view(),name="send"),
]

settings/urls.py
from django.urls import path
from .views import SettingsView

app_name = "settings"
urlpatterns = [
	path("",SettingsView.as_view(),name="list"),
]

user/urls.py
from django.urls import path,include
from .views import * #RegisterView,EditView,SettingsView,ProfileView,EditPersonalView
from django.contrib.auth.views import LogoutView
from user.contract_views import *
from user.edit_views import *

app_name = "user"

contract_patterns = [
	path('',ContractsList.as_view(),name="contracts"),
	path('create/',ContractCreate.as_view(),name="contract_create"),
	path('<slug>-<pk>/',ContractView.as_view(),name="contract_detail"),
	path('<pk>/edit/',ContractEdit.as_view(),name="contract_edit"),
	path('<pk>/applications/',ContractApplications.as_view(),name="contract_applications"),
	path('<pk>/applications-<app_pk>/',ContractApplicationAccept,name="application_accept"),
	path('<pk>/applications-<app_pk>/',ContractApplicationDeny,name="application_deny"),
]

edit_patterns = [
	path('personal/',EditPersonalView.as_view(),name="edit_personal"),
	path('contact/',EditContactView.as_view(),name="edit_contact"),
	path('bank-account/',EditBankView.as_view(),name="edit_bank_account"),
	path('occupations/',EditOccupationView.as_view(),name="edit_occupations"),
	path('profile-image/',EditProfileImage.as_view(),name="edit_profile_image"),
]

urlpatterns = [
	path("",ProfileView.as_view(),name="profile"),
	path('logout/',LogoutView.as_view(next_page = "user:login"),name="logout"),
	path('', include("django.contrib.auth.urls")),
	path("register",RegisterView,name="register"),
	path("edit-",include(edit_patterns)),
	path('contracts/',include(contract_patterns)),
]

workers/urls.py
from django.urls import path, include
from .views import *

app_name = "workers"
urlpatterns = [
	path("",WorkersList.as_view(),name="all"),
	path("<slug:username>/",WorkerDetail.as_view(),name="detail"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.

class HomePageView(TemplateView):
	template_name = "index.html"

home/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel='stylesheet' href='{% static "/css/uikit.min.css" %}' />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel='stylesheet' href="{% static 'styles.css' %}"/>
	<script src='{% static "/js/jquery.min.js" %}'></script>
	<script src='{% static "/js/uikit.min.js" %}'></script>
	<script src='{% static "/js/uikit-icons.min.js" %}'></script>
	<script src="{% static "/js/notificationsPoll.js" %}"></script>
	<title>{% block title %}{% endblock title %} | HandyMan</title>
</head>
<body>

	{% block nav %}
    	<div uk-sticky="animation: uk-animation-slide-top; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-light; top: 200">
				<nav class="uk-navbar-container uk-navbar-transparent uk-position-z-index" uk-navbar>
					<div class="uk-navbar-center">
						<div class="uk-navbar-center-left">
							<div>
								<ul class="uk-navbar-nav">
									<li><a href="{% url 'workers:all' %}">Get a HandyMan</a></li>
									<li><a href="{% url 'user:login' %}">Be a HandyMan</a></li>
									<li><a href="/jobs/">HandyMan Jobs</a></li>
								</ul>
							</div>
						</div>
						<a class="uk-navbar-item uk-logo" href="#">Logo</a>
						<div class="uk-navbar-center-right">
							<div>
								<ul class="uk-navbar-nav">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
								</ul>
							</div>
						</div>
					</div>
					{% if user.is_authenticated %}
					<div class="uk-navbar-right">
						<ul class="uk-navbar-nav">
							<li>
								<div class="uk-navbar-item">
									<a href="{% url "user:profile" %}" class="uk-icon-button" uk-icon="user"></a>
									<div class="uk-navbar-dropdown">
										<ul class="uk-nav uk-navbar-dropdown-nav">
											<li class="uk-nav-header">{{user.username}}</li>
											<li class="uk-nav-divider"></li>
											<li><a href="{% url "message:list" %}"><span class="uk-icon" uk-icon="comments"></span> Messages</a></li>
											{% if user.is_client %}
											<li><a href="{% url "user:contracts" %}"><span class="uk-icon" uk-icon="bolt"></span> Contracts</a></li>
											{% endif %}
											<li><a href="{% url "notifications:list" %}" id="notifications">
												<span uk-icon="bell" class="uk-icon"></span><span class="uk-text-small count uk-invisible"></span>
														Notifications
												</a>
											</li>
											<li><a href="{% url "settings:list" %}"><span class="uk-icon" uk-icon="settings"></span> Settings</a></li>
											<li><a href="{% url "user:logout" %}"><span class="uk-icon" uk-icon="sign-out"></span> Logout</a></li>
										</ul>
									</div>
								</div>
							</li>
						</ul>
					</div>
					{% endif %}
				</nav>
			</div>
		{% endblock %}

   <main>{% block content %}{% endblock %}</main>

	 <footer>
		<h3>HandyMan!</h3>
		<p>Connect with us</p>
		<a href="" class="uk-icon-button" uk-icon="twitter"></a>
		<a href="" class="uk-icon-button" uk-icon="facebook"></a>
		<a href="" class="uk-icon-button" uk-icon="instagram"></a>
	</footer>
 </body>
 </html>

home/templates/index.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
	
	<div class="uk-inline uk-width-1-1 low-hero">
		<div class="uk-background-cover" style="background-image:url(/static/images/img1-1.jpeg)" uk-height-viewport>
			<div class="uk-position-cover uk-overlay uk-overlay-primary" id="cover">
				<div class="uk-position-center">
					<h1 class="uk-heading-medium">You need a guy for the job?</h1>
			  	<span class="uk-text-lead">Well, you're in luck!   We've got them all!!</span>
				  <a href='{% url 'workers:all' %}' class="uk-display-block round-button">
			  		<i class="fa fa-search"></i> 
			  		Get a HandyMan
			  	</a>
				</div>
			</div>
		</div>
	</div>


<section class="uk-section uk-section-muted uk-section-large" id="s-1">
	<div class="uk-container">
	<div class="uk-child-width-1-2" uk-grid>
		<div class="uk-padding">
			<h3 class="uk-heading-small s-heading ">Best HandyMen</h3>
			<p class="uk-text-lead sub-heading">We the HandyMan people get fresh jobs wey go blow your mind</p>
			<p>In all of Eastern Nigeria, our HandyMen have been proven to be the best and most reliable workers. We have a reason why it remains so</p>
			<a href="#" class="round-button">Know More About Us</a>
		</div>
		<div>
			<img src='{% static "/images/img8.jpg" %}'>
		</div>
	</div>
	</div>
</section>

<section class="uk-section uk-section-secondary uk-section-large" id="q-1">
	<div class="uk-container">
		<h3 class="uk-heading-small s-heading  uk-heading-line uk-text-right uk-padding"><span>Why You Should Trust Us?</span></h3>
		<div class='uk-child-width-1-3' uk-grid>
	    <div class="">
	      <a href='#'>
	        <img class="uk-border-circle" width=250 height=250 src='{% static "/images/hammer-icon.png" %}'  alt='carpentry'/>
	      	<h4 class='card-title'>Security</h4>
	      </a>
	      <p>We employ high standard security checks and measures to ensure our HandyMen are accountable. We verify their records via their BVNs which is provided upon registration.
	      </p>
	    </div>

    <div class="">
	    <a href='#'>
	      <img class="uk-border-circle" width=250 height=250 src='{% static "images/plier1-icon.png" %}' alt='carpentry'/>
	    	<h4 class='card-title'>Two-way Authentication</h4>
	    </a>
	    <p>Payments for job(s) done is/are not transferred till both the client and the HandyMan indicate that the work is completed. So, your money is not running anywhere.
	    </p>
	  </div>

    <div class="">
	    <a href='#'>
	      <img class="uk-border-circle" width=250 height=250 src='{% static "images/constructor-icon.png" %}' alt='carpentry'/>
		    <h4 class='card-title'>Quality Work</h4>
	    </a>
		  <p>Our handymen are the best that can be found anywhere. Various screening processes ensure we pick the best for you. You sure can trust us.
	  	</p>
	  </div>
	</div>
	<div class="uk-text-center uk-margin uk-padding">
		<a href="#" class="round-button">More Reasons ...</a>
	</div>

</section>

<section class="uk-background-cover uk-background-fixed uk-section" style="background-image: url({% static "images/img4.jpeg)" %}" uk-height-viewport>
	
	<div class="uk-container uk-text-right">
		<div class="uk-padding">
			<h3 class="uk-heading-small s-heading ">Are you a HandyMan?</h3>
			<p class="uk-text-lead sub-heading">You have skills that are needed here</p>
			<p>Join the HandyMan family <br>
			Get paid for doing good jobs<br>
			No hassles or issues here. Just work and be paid!</p>
			<a href="#" class="round-button">Join Now</a>
		</div>
	</div>
</section>

<section class="uk-section" id="o-1" uk-height-viewport>
	<h3 class="uk-heading-small uk-heading-line uk-text-center uk-margin s-heading"><span>Our HandyMen</span></h3>
	<div class="uk-container">
	<div class="uk-child-width-1-4" uk-grid="masonry:true">

		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src="{% static "images/plumber.png" %}">
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Plumbers</h3>
			</div>
			</div>
		</div>
		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src='{% static "images/mover.png" %}'>
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Movers</h3>
			</div>
			</div>
		</div>
		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src='{% static "images/farmer.png" %}'>
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Farmers</h3>
			</div>
			</div>
		</div>
		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src='{% static "images/miner.png" %}'>
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Miners</h3>
			</div>
			</div>
		</div>
		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src='{% static "images/painter.png" %}'>
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Painters</h3>
			</div>
			</div>
		</div>
		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src='{% static "images/electrician.png" %}'>
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Electricians</h3>
			</div>
			</div>
		</div>
		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src='{% static "images/carpenter.png" %}'>
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Carpenters</h3>
			</div>
			</div>
		</div>
		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src='{% static "images/mechanic.jpg" %}'>
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Mechanics</h3>
			</div>
			</div>
		</div>
		<div>
			<div class="uk-card uk-card-default uk-card-hover uk-card-small">
			<div class="uk-card-media-top">
				<img src='{% static "images/bricklayer.png" %}'>
			</div>
			<div class="uk-card-body">
				<h3 class="uk-card-title">Masons</h3>
			</div>
			</div>
		</div>
	</div>
	<div class="uk-text-center uk-margin uk-padding">
		<a href="#" class="round-button">See All HandyMen</a>
	</div>
	</div>
</section>

{% endblock %}