handy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include("home.urls")),
    path('admin/', admin.site.urls),
    path('workers/', include("workers.urls")),
    path('occupations/', include("occupations.urls")),
    path('user/', include("user.urls")),
    path('contract/', include("contract.urls")),
    path('jobs/', include("jobs.urls")),
    path('notifications/', include("notifications.urls")),
    path('messages/', include("message.urls")),
    path('settings/', include("settings.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomePageView

app_name = "home"
urlpatterns = [
	path("",HomePageView.as_view(),name="index")
]

user/urls.py
from django.urls import path,include
from .views import * #RegisterView,EditView,SettingsView,ProfileView,EditPersonalView
from django.contrib.auth.views import LogoutView
from user.contract_views import *
from user.edit_views import *

app_name = "user"

contract_patterns = [
	path('',ContractsList.as_view(),name="contracts"),
	path('create/',ContractCreate.as_view(),name="contract_create"),
	path('<slug>-<pk>/',ContractView.as_view(),name="contract_detail"),
	path('<pk>/edit/',ContractEdit.as_view(),name="contract_edit"),
	path('<pk>/applications/',ContractApplications.as_view(),name="contract_applications"),
	path('<pk>/applications-<app_pk>/',ContractApplicationAccept,name="application_accept"),
	path('<pk>/applications-<app_pk>/',ContractApplicationDeny,name="application_deny"),
]

edit_patterns = [
	path('personal/',EditPersonalView.as_view(),name="edit_personal"),
	path('contact/',EditContactView.as_view(),name="edit_contact"),
	path('bank-account/',EditBankView.as_view(),name="edit_bank_account"),
	path('occupations/',EditOccupationView.as_view(),name="edit_occupations"),
	path('profile-image/',EditProfileImage.as_view(),name="edit_profile_image"),
]

urlpatterns = [
	path("",ProfileView.as_view(),name="profile"),
	path('logout/',LogoutView.as_view(next_page = "user:login"),name="logout"),
	path('', include("django.contrib.auth.urls")),
	path("register",RegisterView,name="register"),
	path("edit-",include(edit_patterns)),
	path('contracts/',include(contract_patterns)),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class HandyUser(AbstractUser):
	is_client = models.BooleanField("Is A Client",default=False)
	class Meta:
		verbose_name='HandyUser'
		verbose_name_plural='HandyUsers'

workers/models.py
from django.db import models
from user.models import HandyUser as User
from occupations.models import Occupation

# Create your models here.
class Worker(models.Model):
  # TODO: Define fields here
  user = models.OneToOneField(User,on_delete=models.CASCADE)
  occupation = models.ManyToManyField(Occupation)
  years_of_experience = models.SmallIntegerField(default=0)
  phone = models.CharField(max_length=14,null=True)
  state = models.CharField(max_length=20,null=True) 
  city = models.CharField(max_length=20,null=True)
  home = models.CharField(max_length=150,null=True)
  work_email = models.EmailField(null=True)
  birth_date = models.DateField(null=True)
  image = models.ImageField(upload_to="workers")

  BANK_NAME = (
    ("ACC","Access Bank"),
    ("DIA","Diamond Bank"),
    ("ECO","Eco Bank"),
    ("FBN","First Bank"),
    ("FCM","First City Monument Bank"),
    ("GTB","Guaranty Trust Bank"),
    ("KEY","Keystone Bank"),
    ("POL","Polaris Bank"),
    ("STE","Sterling Bank"),
    ("UBA","United Bank for Africa"),
    ("UNI","Union Bank"),
    ("UNT","Unity Bank"),
    ("WEM","Wema Bank"),
    ("ZEN","Zenith Bank"),
  )
  bank_name = models.CharField(max_length=3,choices=BANK_NAME,null=True)
  bank_account_name = models.CharField(max_length=100,null=True)
  bank_account_number = models.CharField(max_length=10,null=True)
  bank_bvn = models.CharField(max_length=11,null=True)
  WORK_STATUS = (
  	("NW","Not Working"),
  	("CW","Currently Working"),
  	("AA","Awaiting Approval"),
  )
  ONLINE_STATUS = (
  	("OF","Offline"),
  	("BU","Busy"),
  	("ON","Online")
  )
  work_status = models.CharField(max_length=2,choices=WORK_STATUS)
  online_status = models.CharField(max_length=2,choices=ONLINE_STATUS)
  class Meta:
  	verbose_name = "Worker"
  	verbose_name_plural = "Workers"

  @property
  def address(self):
    home = self.home
    city = self.city
    state = self.state
    if self.home == None or len(self.home)<2:
      home = ""
    if self.city == None or len(self.city)<2:
      city = ""
    if self.state == None or len(self.state)<2:
      state = ""
    address = home +", "+ city +", "+ state
    if len(address) <5:
      return ""
    return address
  
  def __str__(self):
    return self.user.get_full_name()

  def get_absolute_url(self):
    return reverse("workers:detail",kwargs={username:self.user.username})

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from user.models import HandyUser as User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import DetailView,ListView
from workers.models import Worker
from clients.models import Client
from contract.models import Contract


# Create your views here.

class HandyUserCreationForm(UserCreationForm):
	class Meta:
		model = User
		fields = UserCreationForm.Meta.fields + ('is_client','email')
    
def assignStatus(user,is_client):
	if is_client == 'on':
		return Client(user=user)
	else:
		return Worker(user=user)

def RegisterView(request):
	if request.method == "GET":
		form = HandyUserCreationForm()
	elif request.method == "POST":
		form = HandyUserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			'''Obtain proper user from db and create either Client or Worker model for it
				depending on the 'is_client' value
			'''
			user = User.objects.get(username=request.POST['username'])
			is_client = request.POST['is_client']
			person = assignStatus(user,is_client)
			person.save()

			username = request.POST['username']
			password = request.POST['password1']
			auth_user = authenticate(request,username=username,password=password)
			if auth_user is not None:
				login(request,auth_user)
			return redirect("/user/")
	return render(request,"registration/register.html",{"form":form})


@method_decorator(login_required(),name="dispatch")
class ProfileView(DetailView):
	template_name = "user/index.html"
	context_object_name = "person"

	def get_object(self):
		user = self.request.user
		if user.is_client:
			return Client.objects.get(user=user)
		else:
			return Worker.objects.get(user=user)
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = self.request.user
		if user.is_client:
			all_contracts = Contract.objects.filter(client__user=user).order_by("created_on")
			active_contracts = all_contracts.filter(work_status="AC")
			inactive_contracts = all_contracts.filter(work_status="NB")
			context['contracts'] = all_contracts
			context['active_contracts'] = active_contracts
			context['inactive_contracts'] = inactive_contracts
		return context

user/templates/user/index.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}My Profile: {{user.get_full_name|default:user.username}}{% endblock%}

{% block content %}	
<section class="uk-height-small uk-background-primary low-hero"></section>
	<section class="uk-background-primary uk-padding">
		<h5 class="uk-heading-small s-heading">My Profile</h5>
	</section>

<section class="uk-container uk-padding-large uk-padding-remove-bottom">
		<div uk-grid>
			<div class="uk-inline uk-width-2-3">
				<div class=" uk-padding uk-text-center">
			{% if person.image %}
				<div class="uk-overflow-hidden uk-border-circle uk-height-medium uk-width-medium uk-margin-auto uk-display-block uk-inline">
					<div uk-lightbox>
						<a href="{{person.image.url}}" data-caption="{{user.username}}" data-alt="{{user.username}}-profile-image">
							<img src="{{person.image.url}}" class="uk-display-block uk-margin-auto uk-text-center">
						</a>
					</div>
					<div class="uk-overlay uk-position-bottom-right uk-position-z-index">
						<a href="{% url "user:edit_profile_image" %}" uk-tooltip="Edit Profile Image"  class="uk-icon-button uk-background-primary uk-light " uk-icon="icon:pencil;ratio:1.3"></a>
					</div>
				</div>					
			{% else %}
				<a href="{% url "user:edit_profile_image" %}" class="uk-text-center">
					<span class="uk-icon uk-display-block" uk-icon="icon:image;ratio:8"></span>
					<span class="uk-display-block">Add Profile Image</span>
				</a>
			{%endif%}
					<h6 class="uk-text-lead s-heading uk-heading-line uk-text-center"><span>{{user.username}} ({% if user.is_client %}Client{% else %}Worker{% endif %} Account)</span></h6>
				</div>
			</div>
			<div class="uk-background-muted uk-width-1-3 uk-padding">
				<h6 class="uk-text-lead s-heading uk-heading-line uk-text-center">Overview</h6>
				<div uk-grid>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Account:</p>
					<p class="uk-width-2-3 uk-text-bold">
						{% if user.is_client %}Client</p>{% else %}Worker
					</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Overall Rating:</p>
					<p class="uk-width-2-3 uk-text-bold">{{person.rating|default:"0.0"}}</p>
					{% endif %}

					<p class="uk-width-1-3 uk-text-meta uk-text-bold"># of Active Contracts:</p>
					<p class="uk-width-2-3 uk-text-bold">{{active_contracts.count|default:"0"}}</p>
						
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">
					Number of Jobs {% if user.is_client %}Provided{% else %}Done{% endif %}:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contracts.count|default:"0"}}</p>
				</div>
			</div>
		</div>

	</section>
	 
	<section class="uk-container uk-padding-large uk-padding-remove-bottom">
		<div uk-grid>
			<div class="uk-inline uk-width-2-3">
				<div class="uk-box-shadow-small uk-padding">
					<a uk-tooltip="Edit Personal Details" href="{% url "user:edit_personal" %}" class="uk-icon-button uk-position-medium uk-position-top-right uk-background-primary uk-light" uk-icon="icon:pencil;ratio:1.3"></a>
					<h6 class="uk-text-lead s-heading uk-heading-line"><span>Personal Details</span></h6>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Username:</p>
						<p class="uk-width-2-3 uk-text-bold">{{user.username}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Last Name:</p>
						<p class="uk-width-2-3 uk-text-bold">{{user.last_name|default:"Not Set"}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">First Name:</p>
						<p class="uk-width-2-3 uk-text-bold">{{user.first_name|default:"Not Set"}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Personal Email:</p>
						<p class="uk-width-2-3 uk-text-bold">{{user.email|default:"Not Set"}}</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="uk-container uk-padding-large uk-padding-remove-bottom">
		<div uk-grid>
			<div class="uk-inline uk-width-2-3">
				<div class="uk-box-shadow-small uk-padding">
					<a uk-tooltip="Edit Contact Details" href="{% url "user:edit_contact" %}" class="uk-icon-button uk-position-medium uk-position-top-right uk-background-primary uk-light" uk-icon="icon:pencil;ratio:1.3"></a>
					<h6 class="uk-text-lead s-heading uk-heading-line"><span>Contact Details</span></h6>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Work Email:</p>
						<p class="uk-width-2-3 uk-text-bold">{{user.email|default:"Not Set"}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Phone:</p>
						<p class="uk-width-2-3 uk-text-bold">{{person.phone|default:"Not Set"}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Address (Only Visible to Current Clients):</p>
						<p class="uk-width-2-3 uk-text-bold">{{person.address|default:"Not Set"}}</p>
					</div>
				</div>
			</div>
		</div>
	</section>


	{% if user.is_client is False %}
	<section class="uk-container uk-padding-large uk-padding-remove-bottom">
		<div uk-grid>
			<div class="uk-width-2-3 uk-inline">
				<div class="uk-box-shadow-small uk-padding">
					<a uk-tooltip="Edit Bank Account Details" href="{% url "user:edit_bank_account" %}" class="uk-icon-button uk-position-medium uk-position-top-right uk-background-primary uk-light" uk-icon="icon:pencil;ratio:1.3"></a>
					<h6 class="uk-text-lead s-heading uk-heading-line"><span>Bank Account Details</span></h6>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Account Number:</p>
						<p class="uk-width-2-3 uk-text-bold">{{person.bank_account_number|default:"Not Set"}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Account Name:</p>
						<p class="uk-width-2-3 uk-text-bold">{{person.bank_account_name|default:"Not Set"}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Bank Name:</p>
						<p class="uk-width-2-3 uk-text-bold">{{person.get_bank_name_display|default:"Not Set"}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Bank Verification Number (BVN):</p>
						<p class="uk-width-2-3 uk-text-bold">{{person.bank_bvn|default:"Not Set"}}</p>
					</div>
				</div>
			</div>
		</div>		
	</section>

	<section class="uk-container uk-padding-large uk-padding-remove-bottom">
		<div uk-grid>
			<div class="uk-width-2-3 uk-inline">
				<div class="uk-box-shadow-small uk-padding">
					<a uk-tooltip="Edit Work Details" href="{% url "user:edit_occupations" %}" class="uk-icon-button uk-position-medium uk-position-top-right uk-background-primary uk-light" uk-icon="icon:pencil;ratio:1.3"></a>
					<h6 class="uk-text-lead s-heading uk-heading-line"><span>Work Details</span></h6>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Occupations:</p>
						<p class="uk-width-2-3 uk-text-bold">{{person.occupation.all|join:", "|default:"Not Set"}}</p>
					</div>
					<div uk-grid>
						<p class="uk-width-1-3 uk-text-meta uk-text-bold">Years of Experience:</p>
						<p class="uk-width-2-3 uk-text-bold">{{person.years_of_experience|default:"Not Set"}}</p>
					</div>
				</div>
			</div>
		</div>		
	</section>
	{% endif %}

<aside class="uk-padding">
	<h6 class="s-heading uk-text-warning uk-text-center">All the fields in the sections above must be filled before you can be allowed to work or hire a worker</h6>
</aside>
						

{% if user.is_client %}
<section class="uk-container uk-padding-large uk-padding-remove-top">
	<div uk-grid>
		<div class="uk-width-2-3 uk-inline">
			<div class="uk-box-shadow-small uk-padding">
				<a uk-tooltip="Create New Contract" href="{% url "user:contract_create" %}" class="uk-icon-button uk-position-medium uk-position-top-right uk-background-primary uk-light" uk-icon="icon:plus;ratio:1"></a>
				<h6 class="uk-text-lead s-heading uk-heading-line"><span>Contracts</span></h6>
				<div uk-grid>
					<a href="{% url "user:contracts" %}" class="uk-width-1-3 uk-text-meta uk-text-bold">Total Contracts:</a>
					<a href="{% url "user:contracts" %}" class="uk-width-2-3 uk-text-bold">{{contracts.count}}</a>
					<hr class="uk-width-1-1">

					<a href="{% url "user:contracts" %}" class="uk-width-1-3 uk-text-meta uk-text-bold">Active Contracts:</a>
					<a href="{% url "user:contracts" %}" class="uk-width-2-3 uk-text-bold">{{active_contracts.count|default:"0"}}</a>
					<hr class="uk-width-1-1">

					<a class="uk-width-1-3 uk-text-meta uk-text-bold">Contracts Not Started:</a>
					<a class="uk-width-2-3 uk-text-bold">{{inactive_contracts.count|default:"0"}}</a>

				</div>
			</div>
		</div>
	</div>		
</section>
{% endif %}

{% endblock %}