contract/urls.py
from django.urls import path, include
from .views import *

app_name = "contract"
urlpatterns = [
	path('',ContractList.as_view(),name="all"),
	path('<slug>-<pk>/',ContractView.as_view(),name="detail"),
]

handy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include("home.urls")),
    path('admin/', admin.site.urls),
    path('workers/', include("workers.urls")),
    path('occupations/', include("occupations.urls")),
    path('user/', include("user.urls")),
    path('contract/', include("contract.urls")),
    path('jobs/', include("jobs.urls")),
    path('notifications/', include("notifications.urls")),
    path('messages/', include("message.urls")),
    path('settings/', include("settings.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomePageView

app_name = "home"
urlpatterns = [
	path("",HomePageView.as_view(),name="index")
]

user/urls.py
from django.urls import path,include
from .views import * #RegisterView,EditView,SettingsView,ProfileView,EditPersonalView
from django.contrib.auth.views import LogoutView
from user.contract_views import *
from user.edit_views import *

app_name = "user"

contract_patterns = [
	path('',ContractsList.as_view(),name="contracts"),
	path('create/',ContractCreate.as_view(),name="contract_create"),
	path('<slug>-<pk>/',ContractView.as_view(),name="contract_detail"),
	path('<pk>/edit/',ContractEdit.as_view(),name="contract_edit"),
	path('<pk>/applications/',ContractApplications.as_view(),name="contract_applications"),
	path('<pk>/applications-<app_pk>/',ContractApplicationAccept,name="application_accept"),
	path('<pk>/applications-<app_pk>/',ContractApplicationDeny,name="application_deny"),
]

edit_patterns = [
	path('personal/',EditPersonalView.as_view(),name="edit_personal"),
	path('contact/',EditContactView.as_view(),name="edit_contact"),
	path('bank-account/',EditBankView.as_view(),name="edit_bank_account"),
	path('occupations/',EditOccupationView.as_view(),name="edit_occupations"),
	path('profile-image/',EditProfileImage.as_view(),name="edit_profile_image"),
]

urlpatterns = [
	path("",ProfileView.as_view(),name="profile"),
	path('logout/',LogoutView.as_view(next_page = "user:login"),name="logout"),
	path('', include("django.contrib.auth.urls")),
	path("register",RegisterView,name="register"),
	path("edit-",include(edit_patterns)),
	path('contracts/',include(contract_patterns)),
]

workers/urls.py
from django.urls import path, include
from .views import *

app_name = "workers"
urlpatterns = [
	path("",WorkersList.as_view(),name="all"),
	path("<slug:username>/",WorkerDetail.as_view(),name="detail"),
]

contract/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from workers.models import Worker
from clients.models import Client
from occupations.models import Occupation

# Create your models here.
WORK_STATUS = (
	("NB","Not Begun"),
	("AC","Active"),
	("CO","Completed")
)
WORK_TYPE = (
	("ST","Short Term"),
	("LT","Long Term"),
	("OT","One Time")
)

class Contract(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()
	client = models.ForeignKey(Client,on_delete=models.CASCADE)
	workers = models.ManyToManyField(Worker)
	wage = models.IntegerField(default=0)
	slug = models.SlugField(null=True)
	work_type = models.CharField(max_length=2,choices=WORK_TYPE,default='OT')
	client_approved = models.BooleanField(default=False)
	worker_done = models.BooleanField(default=False)
	work_status = models.CharField(max_length=2,choices=WORK_STATUS,default='NB')
	rating = models.SmallIntegerField(default=0)
	created_on = models.DateTimeField(auto_now_add=True)
	edited_on = models.DateTimeField(auto_now=True)
	finished_on = models.DateTimeField(null=True,editable=False)
	occupations = models.ManyToManyField(Occupation)
	num_of_workers = models.SmallIntegerField(default=1)
	years_of_experience = models.SmallIntegerField(default=0)
	location = models.CharField(max_length=300,default="")

	class Meta:
		verbose_name = "Contract"
		verbose_name_plural = "Contracts"

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("contract:detail",kwargs={"pk":self.id,"slug":self.slug})

	def finished(self):
		if self.client_approved==True and self.worker_done==True:
			self.work_status = "CO"
			now = timezone.now()
			self.finished_on = now
			return True
		return False
	def save(self,*args,**kwargs):
		value = self.title
		self.slug = slugify(value, allow_unicode=True)
		super().save(*args,**kwargs)
		
		    
class Application(models.Model):
	contract = models.ForeignKey(Contract,on_delete=models.CASCADE)
	worker = models.ForeignKey(Worker,on_delete=models.CASCADE)
	applied_on = models.DateTimeField(auto_now_add=True)
	message = models.TextField()
	seen = models.BooleanField(default=False)
	accepted = models.BooleanField(default=False)

	class Meta:
		verbose_name='Application'
		verbose_name_plural = 'Applications'

	def __str__(self):
		return "%s's application to %s" % (self.worker.user.username,self.contract.title)

	def get_absolute_url(self):
		pk = self.contract.pk
		slug = self.contract.slug
		return reverse("jobs:applied",kwargs={"pk":pk,"slug":slug})

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class HandyUser(AbstractUser):
	is_client = models.BooleanField("Is A Client",default=False)
	class Meta:
		verbose_name='HandyUser'
		verbose_name_plural='HandyUsers'

contract/views.py
from django.views.generic import ListView,DetailView,UpdateView
from .models import Contract,Application

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.

login_url = "/user/login/"

class ContractView(DetailView):
	model = Contract
	template_name = "contract.html"
	context_object_name = "contract"
	query_pk_and_slug = True



@method_decorator(login_required(login_url=login_url),name="dispatch")
class ContractList(ListView):
	model = Contract
	template_name = "all_contracts.html"
	context_object_name = "contracts"
	ordering = ['-created_on']

class Application(UpdateView):
	pass

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from user.models import HandyUser as User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import DetailView,ListView
from workers.models import Worker
from clients.models import Client
from contract.models import Contract


# Create your views here.

class HandyUserCreationForm(UserCreationForm):
	class Meta:
		model = User
		fields = UserCreationForm.Meta.fields + ('is_client','email')
    
def assignStatus(user,is_client):
	if is_client == 'on':
		return Client(user=user)
	else:
		return Worker(user=user)

def RegisterView(request):
	if request.method == "GET":
		form = HandyUserCreationForm()
	elif request.method == "POST":
		form = HandyUserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			'''Obtain proper user from db and create either Client or Worker model for it
				depending on the 'is_client' value
			'''
			user = User.objects.get(username=request.POST['username'])
			is_client = request.POST['is_client']
			person = assignStatus(user,is_client)
			person.save()

			username = request.POST['username']
			password = request.POST['password1']
			auth_user = authenticate(request,username=username,password=password)
			if auth_user is not None:
				login(request,auth_user)
			return redirect("/user/")
	return render(request,"registration/register.html",{"form":form})


@method_decorator(login_required(),name="dispatch")
class ProfileView(DetailView):
	template_name = "user/index.html"
	context_object_name = "person"

	def get_object(self):
		user = self.request.user
		if user.is_client:
			return Client.objects.get(user=user)
		else:
			return Worker.objects.get(user=user)
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = self.request.user
		if user.is_client:
			all_contracts = Contract.objects.filter(client__user=user).order_by("created_on")
			active_contracts = all_contracts.filter(work_status="AC")
			inactive_contracts = all_contracts.filter(work_status="NB")
			context['contracts'] = all_contracts
			context['active_contracts'] = active_contracts
			context['inactive_contracts'] = inactive_contracts
		return context

user/templates/user/contracts/contract.html
{% extends "base_generic.html" %}
{% load static %}
{% load humanize  %}
{% block title %}Contract: {{contract.title}}{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-secondary low-hero"></section>
<section class="uk-background-secondary uk-padding">
	<h5 class="uk-heading-small s-heading uk-light">Contract: {{contract.title}}</h5>
</section>

<section class="uk-container uk-padding-large uk-padding-remove-top">
	<div class="uk-child-width-1-1" uk-grid>
		<div class="uk-inline">
			<div class="uk-box-shadow-small uk-padding">
				<p class="uk-text-right">
					<a href="{% url "user:contract_applications" contract.pk %}" class="uk-icon-button uk-background-primary uk-light" uk-icon="bolt" uk-tooltip="Applications"></a>
					<a href="{% url "user:contract_edit" contract.pk %}" class="uk-icon-button uk-background-secondary " uk-icon="pencil" uk-tooltip="Edit contract details"></a>
				</p>

				<div uk-grid>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Applications:</p>
					<p class="uk-width-2-3 uk-text-bold">{{applications.count|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Contract ID:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.id|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Contract Description:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.description|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Contract Payment:</p>
					<p class="uk-width-2-3 uk-text-bold">₦ {{contract.wage|intcomma|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Contract Type:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.get_work_type_display|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Contract Created On:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.created_on|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Occupations Needed:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.occupations.all|join:", "|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Number of Workers Needed:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.num_of_workers|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Contract Location:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.location|default:"Not Set"}}</p>
				</div>
				
			</div>
		</div>
	</div>
</section>

{% endblock %}

user/templates/user/contracts/contract_applications.html
{% extends "base_generic.html" %}
{% load static %}
{% load humanize  %}
{% block title %}Contract: {{applications.0.contract.title}} Applications{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-secondary low-hero"></section>
<section class="uk-background-secondary uk-padding">
	<h5 class="uk-heading-small s-heading uk-light">Applications to Contract: {{applications.0.contract.title}}</h5>
</section>

<section class="uk-container uk-padding-large uk-padding-remove-top">
	<div class="uk-child-width-1-1" uk-grid>
		<div class="uk-inline">
			<div class=" uk-padding">
				<div uk-grid>
					<p class="uk-text-center">{{applications.count}} application{{applications.count|pluralize}}</p>
					{% for application in applications %}
					<div class="uk-width-1-1 uk-box-shadow-small uk-padding" >
						<p>
							<span class="uk-icon" uk-icon="user"></span>
							<a href="{% url "workers:detail" application.worker.user.username %}">{{application.worker.user.username}}</a>
							<span>Applied on {{application.applied_on}}</span>
							<div>
								<span class="uk-icon" uk-icon="cog"></span>
								{% for occupation in application.worker.occupation.all %}
								<span class="chip" uk-tooltip="{{occupation.description}}">{{occupation}}</span>
								{% empty %}
								No Occupation set
								{% endfor %}
							</div>
						</p>
						<p><span class="uk-icon" uk-icon="location"></span> {{application.worker.address|default:"No Location Set"}}</p>
						<p>
							<span class="uk-icon" uk-icon="comment"></span>
							{{application.message}} 
						</p>
						<input type="hidden" name="worker_username" value="{{application.worker.user.username}}">

						{% if application.accepted == False %}

						<form action="{% url "user:application_accept" application.contract.pk application.pk %}" method="POST" class="uk-display-inline-block">
							{% csrf_token %}
							<button class="uk-button-primary uk-button" type="submit"><span class="uk-icon" uk-icon="check"></span> Accept Worker</button>
						</form>
						<form action="{% url "user:application_deny" application.contract.pk application.pk %}" method="POST" class="uk-display-inline-block">
							{% csrf_token %}
							<button class="uk-button-danger uk-button" type="submit" formmethod="POST" formaction="{% url "user:application_deny" application.contract.pk application.pk %}"><span class="uk-icon" uk-icon="close"></span> Reject Worker</button>
						</form>

						{% else %}
						<hr>
						<p class="uk-text-bold">Application Accepted</p>

						{% endif %}

					</div>
					<hr class="uk-width-1-1">
					{% endfor %}
				</div>
				
			</div>
		</div>
	</div>
</section>

{% endblock %}

user/templates/user/contracts/contract_create.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}Create Contract{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-secondary low-hero"></section>
<section class="uk-background-secondary uk-padding">
	<h5 class="uk-heading-small s-heading uk-light">Create Contract</h5>
</section>

<section class="uk-container">
	<div class="uk-section uk-padding">
		
		<form action="{% url "user:contract_create" %}" method="POST" class="uk-form-stacked">
			{% csrf_token %}
			<div class="uk-margin">
				<label>Job Title</label>
				<div class="uk-form-controls">
					{{form.title}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Job Description</label>
				<div class="uk-form-controls">
					{{form.description}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Wage (Payment for one worker)</label>
				<div class="uk-form-controls">
					{{form.wage}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Job Type</label>
				<div class="uk-form-controls">
					{{form.work_type}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Occupations Needed</label>
				<div class="uk-form-controls">
					{{form.occupations}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Years of Experience required</label>
				<div class="uk-form-controls">
					{{form.years_of_experience}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Number of Workers Wanted</label>
				<div class="uk-form-controls">
					{{form.num_of_workers}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Job Location <span class="uk-icon" uk-icon="info"uk-tooltip="This is shown only to the worker(s) you hire for the job"></span></label>
				<div class="uk-form-controls">
					{{form.location}}
				</div>
			</div>
			<div class="uk-margin">
				<button type="submit" class="uk-button uk-button-secondary">Submit</button>
			</div>
		</form>
	</div>

</section>

<script type="text/javascript">
	$("input").addClass("uk-input")
	$("textarea").addClass("uk-textarea")
	$("select").addClass("uk-select")
</script>
{% endblock %}

user/templates/user/contracts/contract_edit.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}Editing Contract: {{contract.title}}{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-secondary low-hero"></section>
<section class="uk-background-secondary uk-padding">
	<h5 class="uk-heading-small s-heading uk-light">Edit Contract: {{contract.title}}</h5>
</section>

<section class="uk-container">
	<div class="uk-section uk-padding">
		
		<form action="{% url "user:contract_edit" contract.pk %}" method="POST" class="uk-form-stacked">
			{% csrf_token %}
			<div class="uk-margin">
				<label>Job Title</label>
				<div class="uk-form-controls">
					{{form.title}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Job Description</label>
				<div class="uk-form-controls">
					{{form.description}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Wage (Payment for one worker)</label>
				<div class="uk-form-controls">
					{{form.wage}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Job Type</label>
				<div class="uk-form-controls">
					{{form.work_type}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Occupations Needed</label>
				<div class="uk-form-controls">
					{{form.occupations}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Number of Workers Wanted</label>
				<div class="uk-form-controls">
					{{form.num_of_workers}}
				</div>
			</div>
			<div class="uk-margin">
				<label>Job Location <span class="uk-icon" uk-icon="info" uk-tooltip="This is shown only to the worker(s) you hire for the job"></span></label>
				<div class="uk-form-controls">
					{{form.location}}
				</div>
			</div>
			<div class="uk-margin">
				<button type="submit" class="uk-button uk-button-secondary">Submit</button>
			</div>
			<div>
				<p>Contract originally created on {{contract.created_on}}.</p>
				{% if contract.created_on is not contract.edited_on %}
				<p>Contract last edited on {{contract.edited_on}}</p>
			</div>
			{% endif %}
		</form>
	</div>

</section>

<script type="text/javascript">
	$("#id_title,#id_wage,#id_num_of_workers,#id_location").addClass("uk-input")
	$("#id_description").addClass("uk-textarea")
	$("#id_work_type,#id_occupations").addClass("uk-select")
</script>
{% endblock %}

user/templates/user/contracts/index.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}My Profile: {{user.get_full_name|default:user.username}}{% endblock%}

{% block content %}	
<section class="uk-height-small uk-background-primary low-hero"></section>
	<section class="uk-background-primary uk-padding">
		<h5 class="uk-heading-small s-heading">My Contracts</h5>
	</section>

	<section class="uk-container uk-padding-large">
		<div class="uk-text-right uk-margin-bottom uk-text-bold uk-text-meta">
			<p>{{contracts.count}} contract{{contracts.count|pluralize}}</p>
			<hr>
		</div>
		<ul uk-accordion="multiple:true; active:0">
		{% for contract in contracts %}
			<li uk-grid>
				<span class="uk-accordion-title uk-width-expand">{{contract.title|truncatewords:20}}</span>
					<span class="uk-float-right uk-width-auto">
						<a href="{% url "user:contract_detail" contract.slug contract.pk %}" uk-icon="icon:info;ratio:1.8" class="uk-icon"></a>
						<a href="{% url "user:contract_edit" contract.pk %}" uk-icon="pencil" class="uk-icon-button uk-background-primary uk-light"></a>
						<a href="#" uk-icon="trash" class="uk-icon-button uk-background-secondary"></a>
					</span>
				<div class="uk-accordion-content uk-padding uk-padding-remove-vertical uk-text-small uk-text-meta uk-width-1-1">
					{{contract.description}}
					<p class="uk-text-bold">Created on {{contract.created_on}}</p>
				<hr>
				</div>
			</li>
		{% endfor %}
		</ul>
	</section>
{% endblock %}