handy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include("home.urls")),
    path('admin/', admin.site.urls),
    path('workers/', include("workers.urls")),
    path('occupations/', include("occupations.urls")),
    path('user/', include("user.urls")),
    path('contract/', include("contract.urls")),
    path('jobs/', include("jobs.urls")),
    path('notifications/', include("notifications.urls")),
    path('messages/', include("message.urls")),
    path('settings/', include("settings.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomePageView

app_name = "home"
urlpatterns = [
	path("",HomePageView.as_view(),name="index")
]

jobs/urls.py
from django.urls import path, include
from .views import *

app_name = "jobs"
urlpatterns = [
	path('',ContractList.as_view(),name="all"),
	path('page-<int:page>/',ContractPage.as_view(),name="page"),
	path('<slug>-<pk>/',ContractView.as_view(),name="detail"),
	path('<slug>-<pk>/apply/',ContractApplyView.as_view(),name="apply"),
	path('<slug>-<pk>/application/',ContractApplied.as_view(),name="applied"),
	path('search/',SearchView.as_view(),name="search"),
	path('search/<item>/',SearchView.as_view(),name="search_item"),
]

contract/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from workers.models import Worker
from clients.models import Client
from occupations.models import Occupation

# Create your models here.
WORK_STATUS = (
	("NB","Not Begun"),
	("AC","Active"),
	("CO","Completed")
)
WORK_TYPE = (
	("ST","Short Term"),
	("LT","Long Term"),
	("OT","One Time")
)

class Contract(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()
	client = models.ForeignKey(Client,on_delete=models.CASCADE)
	workers = models.ManyToManyField(Worker)
	wage = models.IntegerField(default=0)
	slug = models.SlugField(null=True)
	work_type = models.CharField(max_length=2,choices=WORK_TYPE,default='OT')
	client_approved = models.BooleanField(default=False)
	worker_done = models.BooleanField(default=False)
	work_status = models.CharField(max_length=2,choices=WORK_STATUS,default='NB')
	rating = models.SmallIntegerField(default=0)
	created_on = models.DateTimeField(auto_now_add=True)
	edited_on = models.DateTimeField(auto_now=True)
	finished_on = models.DateTimeField(null=True,editable=False)
	occupations = models.ManyToManyField(Occupation)
	num_of_workers = models.SmallIntegerField(default=1)
	years_of_experience = models.SmallIntegerField(default=0)
	location = models.CharField(max_length=300,default="")

	class Meta:
		verbose_name = "Contract"
		verbose_name_plural = "Contracts"

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("contract:detail",kwargs={"pk":self.id,"slug":self.slug})

	def finished(self):
		if self.client_approved==True and self.worker_done==True:
			self.work_status = "CO"
			now = timezone.now()
			self.finished_on = now
			return True
		return False
	def save(self,*args,**kwargs):
		value = self.title
		self.slug = slugify(value, allow_unicode=True)
		super().save(*args,**kwargs)
		
		    
class Application(models.Model):
	contract = models.ForeignKey(Contract,on_delete=models.CASCADE)
	worker = models.ForeignKey(Worker,on_delete=models.CASCADE)
	applied_on = models.DateTimeField(auto_now_add=True)
	message = models.TextField()
	seen = models.BooleanField(default=False)
	accepted = models.BooleanField(default=False)

	class Meta:
		verbose_name='Application'
		verbose_name_plural = 'Applications'

	def __str__(self):
		return "%s's application to %s" % (self.worker.user.username,self.contract.title)

	def get_absolute_url(self):
		pk = self.contract.pk
		slug = self.contract.slug
		return reverse("jobs:applied",kwargs={"pk":pk,"slug":slug})

jobs/models.py
from django.db import models

# Create your models here.

jobs/views.py
from django.views.generic import ListView,DetailView,CreateView,UpdateView
from contract.models import Contract,Application
from django.db.models import Q

# from occupations.models import Occupation
from clients.models import Client
from workers.models import Worker

from notifications.models import Notification

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.

class ContractView(DetailView):
	model = Contract
	template_name = "job_detail.html"
	context_object_name = "contract"
	query_pk_and_slug = True
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		applied = None
		if self.request.user.is_authenticated:
			if self.request.user.is_client is False:
				if Application.objects.filter(contract=self.get_object(),worker__user=self.request.user):
					applied = "Applied"
				context['applied'] = applied
			elif self.request.user.is_client:
				context['applied'] = "Clients cannot apply for jobs"
		return context


class ContractList(ListView):
	model = Contract
	template_name = "all_jobs.html"
	context_object_name = "contracts"
	ordering = ['-created_on']
	paginate_by = 2


class ContractPage(ListView):
	model = Contract
	template_name = "all_jobs.html"
	context_object_name = "contracts"
	ordering = ['-created_on']
	paginate_by = 2


@method_decorator(login_required(),name="dispatch")
class ContractApplyView(CreateView):
	model = Application
	template_name = "apply.html"
	context_object_name = "application"
	fields = ['message']

	def form_valid(self,form):
		slug = self.kwargs.get('slug')
		pk = self.kwargs.get('pk')
		form.instance.contract = Contract.objects.get(slug=slug,pk=pk)
		form.instance.worker = Worker.objects.get(user=self.request.user)
		applications = Application.objects.filter(contract = form.instance.contract,seen=False)
		notification = Notification(user=form.instance.contract.client.user,notification_type="NA")
		notification.create_message(
			contract = form.instance.contract,
			application_count = applications.count()
		)
		notification.save()
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    slug,pk = self.kwargs['slug','pk']
	    contract = Contract.objects.get(slug=slug,pk=pk)
	    context['contract']=contract
	    return context


@method_decorator(login_required(),name="dispatch")
class ContractApplied(DetailView):
	template_name = "application.html"
	context_object_name = "application"
	def get_object(self):
		pk,slug = self.kwargs['pk','slug']
		application = Application.objects.get(contract__slug=slug,contract__pk=pk,worker__user=self.request.user)
		return application



class SearchView(ListView):
	template_name = "search.html"
	context_object_name = "contracts"

	def get_queryset(self):
		item = self.kwargs.get('item') or ""
		self.extra_context = {"item": item}
		return Contract.objects.filter(
			Q(title__icontains=item) | 
			Q(description__icontains=item) |
			Q(occupations__name__icontains=item)
			).order_by("-created_on")

jobs/templates/all_jobs.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}Jobs{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-primary low-hero"></section>
<section class="uk-background-primary uk-padding">
	<h5 class="uk-heading-small s-heading uk-light">All Jobs</h5>
</section>

<section class="uk-container uk-padding-large">

			<form class="uk-search uk-search-large uk-search-default uk-width-3-4 uk-margin" action="{% url "jobs:search" %}" method="GET">
		    <button type="submit" uk-search-icon class="uk-search-icon-flip"></button>
			  <input class="uk-search-input uk-border-pill" type="search" placeholder="Search for Jobs or Occupations" name="filter">
			</form>
	<div uk-grid>
		<section class="uk-width-3-4 uk-padding">

			
		{% for contract in contracts %}
			<article class="uk-section uk-box-shadow-small uk-margin uk-padding">
				<div uk-grid>
					<h6 class="s-heading uk-width-expand"><a href="{% url "jobs:detail" contract.slug contract.id %}">{{contract.title}}</a></h6>
					<div class="notif-icons uk-width-auto">
						{{contract.created_on|timesince}} ago
					</div>
					<p class="uk-width-1-1">{{contract.description|truncatewords:50}}</p>
					
				</div>
			</article>
		{% endfor %}
			{# {{page_obj.number}} of {{paginator.num_pages}} #}

		<ul class="uk-pagination uk-flex-right">
			{% if page_obj.has_previous %}
			<li><a href="{% url "jobs:page" page_obj.previous_page_number %}"><span uk-pagination-previous></span></a></li>
			<li><a href="{% url "jobs:page" 1 %}">First</a></li>
			{% endif %}
			{% for page in paginator.page_range %}
				{% if page_obj.number is page %}
				<li class="uk-active"><a href="{% url "jobs:page" page %}">{{page}}</a></li>
				{% else %}
				<li><a href="{% url "jobs:page" page %}">{{page}}</a></li>
				{% endif %}
			{% endfor %}
			{% if page_obj.has_next %}
			<li><a href="{% url "jobs:page" paginator.num_pages %}">Last</a></li>
			<li><a href="{% url  "jobs:page" page_obj.next_page_number %}"><span uk-pagination-next></span></a></li>
			{% endif %}
		</ul>


		</section>

		<section class="uk-width-1-4 uk-background-secondary uk-light uk-padding uk-hidden">
			<ul>Arrange by
				<li>Date</li> 
				<li>Payment</li> 
			</ul>
		</section>

	</div>
</section>

{% endblock %}

jobs/templates/application.html
{% extends "base_generic.html" %}
{% load static humanize %}
{% block title %}My Application for Job: {{application.contract.title|truncatechars:30}}{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-secondary low-hero"></section>
{# <section class="uk-background-secondary uk-padding"> #}
{# </section> #}

<section class="uk-container ">
	<div class="uk-child-width-1-1" uk-grid>
		<div class="uk-inline">
			<div class="uk-box-shadow-small uk-padding">
				<h4 class="uk-text-lead uk-text-large s-heading uk-margin-medium-bottom">Applied for <i><u>{{application.contract.title}}</u></i></h4>
				<p class="uk-text-meta s-heading">My Message:</p>
				<p>{{application.message}}</p>
				<div>
					<p class="uk-text-meta  uk-text-bold">Job Description:</p>
					<p class="">{{application.contract.description|truncatewords:10|default:"Not Set"}}<a href="{% url "jobs:detail" application.contract.slug application.contract.id %}">Read more</a></p>

				</div>
				
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
	$("textarea").addClass("uk-textarea")
</script>
{% endblock %}

jobs/templates/apply.html
{% extends "base_generic.html" %}
{% load static humanize %}
{% block title %}Apply for Job: {{contract.title|truncatechars:30}}{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-secondary low-hero"></section>
{# <section class="uk-background-secondary uk-padding"> #}
{# </section> #}

<section class="uk-container ">
	<div class="uk-child-width-1-1" uk-grid>
		<div class="uk-inline">
			<div class="uk-box-shadow-small uk-padding">
				<h4 class="uk-text-lead uk-text-large s-heading uk-margin-medium-bottom">{{contract.title}}</h4>

				<form action="{% url "jobs:apply" contract.slug contract.id %}" method="POST" class="uk-form-stacked">
				{% csrf_token %}
					<label class="uk-form-label">Message <span class="uk-text-meta">(Optional)</span></label>
					<div class="uk-form-controls">
						{{form.message}}
					</div>
					<button type="submit" class="uk-button uk-button-primary uk-margin">Apply</button>
				</form>
				<div>
					<p class=" uk-text-meta uk-text-bold">Job Description:</p>
					<p class="">{{contract.description|truncatewords:10|default:"Not Set"}} <a href="{% url "jobs:detail" contract.slug contract.id %}">Read more</a></p>

				</div>
				
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
	$("textarea").addClass("uk-textarea")
</script>
{% endblock %}

jobs/templates/job_detail.html
{% extends "base_generic.html" %}
{% load static humanize %}
{% block title %}Job: {{contract.title|truncatechars:30}}{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-secondary low-hero"></section>
{# <section class="uk-background-secondary uk-padding"> #}
{# </section> #}

<section class="uk-container ">
	<div class="uk-child-width-1-1" uk-grid>
		<div class="uk-inline">
			<div class="uk-box-shadow-small uk-padding">
				<div class="uk-padding uk-padding-remove-horizontal uk-text-right">
					{% if applied %}
					<button class="uk-button-primary uk-button" disabled>{{applied}}</button>
					{% else %}
					<a href="{% url "jobs:apply" contract.slug contract.id %}"><button class="uk-button-primary uk-button">Apply for job</button></a>
					{% endif %}
					<p>
						<span class="uk-icon" uk-icon="calendar"></span>
						{{contract.created_on|date:"d M, Y"}} ({{contract.created_on|naturaltime}})
					</p>
					<p>
						<span class="uk-icon" uk-icon="user"></span>
						{{contract.client.user.get_full_name|default:contract.client.user.username}}
					</p>
				</div>
				<h4 class="uk-text-lead uk-text-large s-heading uk-margin-medium-bottom">{{contract.title}}</h4>
				<div>
					<p class=" uk-text-meta uk-text-bold">Job Description:</p>
					<p class="">{{contract.description|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Job Payment:</p>
					<p class="uk-width-2-3 uk-text-bold">₦ {{contract.wage|intcomma|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Job Type:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.get_work_type_display|default:"Not Set"}}</p>
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Occupations Needed:</p>
					<p class="uk-width-2-3 uk-text-bold">
						{% for occupation in contract.occupations.all %}
							<a class="chip" uk-tooltip="{{occupation.description}}">{{occupation}}</a>
						{% endfor %}
					<p class="uk-width-1-3 uk-text-meta uk-text-bold">Number of Workers Needed:</p>
					<p class="uk-width-2-3 uk-text-bold">{{contract.num_of_workers|default:"Not Set"}}</p>
				</div>
				
			</div>
		</div>
	</div>
</section>

{% endblock %}

jobs/templates/search.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}"{{item}}" Jobs{% endblock %}

{% block content %}
<section class="uk-height-small uk-background-primary low-hero"></section>
<section class="uk-background-primary uk-padding">
	<h5 class="uk-heading-small s-heading uk-light">All Jobs with "{{item}}"</h5>
</section>

<section class="uk-container uk-padding-large">

	<form class="uk-search uk-search-large uk-search-default uk-width-3-4 uk-margin" action="{% url "jobs:search" %}" method="GET">
    <button type="submit" uk-search-icon class="uk-search-icon-flip"></button>
	  <input class="uk-search-input uk-border-pill" type="search" placeholder="Search for Jobs or Occupations" name="filter" value="{{item}}">
	</form>
	<div uk-grid>
		<section class="uk-width-3-4 uk-padding">
		{% for contract in contracts %}
			<article class="uk-section uk-box-shadow-small uk-margin uk-padding">
				<div uk-grid>
					<h6 class="s-heading uk-width-expand"><a href="{% url "jobs:detail" contract.slug contract.id %}">{{contract.title}}</a></h6>
					<div class="notif-icons uk-width-auto">
						{{contract.created_on|timesince}} ago
					</div>
					<p class="uk-width-1-1">{{contract.description|truncatewords:50}}</p>
				</div>
			</article>
		{% endfor %}
		</section>

		<section class="uk-width-1-4 uk-background-secondary uk-light uk-padding uk-hidden">
			<ul>Arrange by
				<li>Date</li> 
				<li>Payment</li> 
			</ul>
		</section>
	</div>
</section>

{% endblock %}